### ISSUE TITLE
Android app crashes on "Click here to select files" while trying to upload Video

### ISSUE THREAD

**Issue by siremystic** [unaio/una-mobile-app#14]
Android app immediately crashes while trying to access phone files library upon all video uploads via any video supporting modules. This happens upon adding video contents via update, ads, post, video, and discussion modules when clicking on "Drop files here to upload or Click here to select files" as seen below:
![vid](https://user-images.githubusercontent.com/47337635/90185762-25a23e00-dd85-11ea-9a97-333ec379379f.PNG)

**Comment by siremystic** [comment]
@AlexT-UNA @AlexTr

**Comment by AlexTr** [comment]
Please could you specify your Android app version ?

**Comment by siremystic** [comment]
Android version 8.1.0  Also i have tired several higher versions still the same... perhaps you try it on your end too

**Comment by AlexTr** [comment]
Could you please specify your UNA Mobile App version as well ? since it should be fixed in some of recent updates

**Comment by siremystic** [comment]
issue still persist...i noticed it works fine on new downloads, after a while app crashes unexpectedly while trying to upload video on trying to access local android gallery as shown earlier

**Comment by siremystic** [comment]
please give priority to this issue @AlexTr @AlexT-UNA

**Comment by AlexTr** [comment]
https://github.com/unaio/una-mobile-app/commit/028f46577caaa9d9ae0e681e8ecf96628e659827
